AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - 'iot:TestInvokeAuthorizer'
            - 'iot:GetOTAUpdateJob'
            - 'iot:Connect'
            - 'iot:GetRegistrationCode'
            - 'iot:DescribeCertificate'
            - 'iot:DescribeEndpoint'
            - 'iot:GetJobDocument'
            - 'iot:UpdateStream'
            - 'iot:Subscribe'
            - 'iot:DescribeRoleAlias'
            - 'iot:GetThingShadow'
            - 'iot:DescribeStream'
            - 'iot:DescribeIndex'
            - 'iot:GetEffectivePolicies'
            - 'iot:Publish'
            - 'iot:GetPolicyVersion'
            - 'iot:GetPolicy'
            - 'iot:GetTopicRule'
            - 'iot:DescribeThing'
            - 'iot:GetIndexingConfiguration'
            - 'iot:GetLoggingOptions'
            - 'iot:SearchIndex'
            - 'iot:UpdateThingShadow'
            - 'iot:Receive'
            - 'iot:TestAuthorization'
            - 'iot:DescribeDefaultAuthorizer'
            - 'iot:DescribeCACertificate'
            - 'iot:UpdateThing'
            - 'iot:DescribeJob'
            - 'iot:DescribeAuthorizer'
            - 'iot:DescribeThingType'
            - 'iot:DescribeJobExecution'
            - 'cloudformation:Describe*'
            - 'cloudformation:List*'
            - 'cloudformation:Get*'
          Resource: '*'
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post